[project]
name = "workout-schedule"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "fastapi>=0.115",
    "psycopg[binary]>=3.2.13",
    "pydantic>=2.9",
    "pyjwt[crypto]>=2.13.0",
    "sqlalchemy>=2.0",
    "uvicorn[standard]>=0.34",
]

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "openpyxl>=3.1.5",
]
